refactor: Implement `cmod` to all components & `@use` utils in other scss components
- add delay() fn to new "utils" dir
- remove icons from "public" dir
- fix error when using one mport '@/assets/styles/main.scss' import for scss instead of multiple for each scss file

ERROR:
src/assets/styles/main.scss
Error: [sass] Error: Plain CSS functions don't support keyword arguments.
     background-color: cmod(currentColor, $a: 0.1);